# spring.application.name=portfolio-backend
# server.port=8080
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=faourhadi0@gmail.com
# spring.mail.password=digv gnbg rfxu jmju
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

portfolio.contact.to=faourhadi0@gmail.com

spring.application.name=portfolio-backend

server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=faourhadi0@gmail.com
spring.mail.password=digv gnbg rfxu jmju

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

portfolio.contact.to=faourhadi0@gmail.com
